<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>XZip.Helper</RootNamespace>
    <AssemblyName>xzip-helper</AssemblyName>
    <PublishAot>false</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XZip.Core\XZip.Core.csproj" />
  </ItemGroup>

</Project>
