<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>XZip.Core</RootNamespace>
    <AssemblyName>XZip.Core</AssemblyName>
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" />
    <PackageReference Include="SharpZipLib" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="System.Threading.Tasks.Dataflow" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="XZip.Core.Tests" />
  </ItemGroup>

</Project>
